# action.yaml
name: 'Custom GitHub Action'
description: 'A GitHub Action that takes a message and prints it'
inputs:
	num:
    description: 'Enter a message'
    required: true
    default: "Hello World!"
outputs:
  num_squared:
    description: 'Message of the input'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
              echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch the number's square
      id: get-square
      run: python src/get_num_square.py
      shell: bash
